[package]
name = "memory-nexus-v1"
version = "1.0.0"
edition = "2021"
rust-version = "1.75"

[[bin]]
name = "memory-nexus-v1"
path = "src/simple_main.rs"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }