# Memory Nexus - Main Docker Compose
# This file references the appropriate Docker configuration based on your needs
#
# Usage:
#   Development:  docker-compose up -d
#   Production:   docker-compose -f docker/docker-compose.prod.yml up -d
#   Simple test:  docker-compose -f docker/docker-compose.simple.yml up -d

# Default configuration extends the development setup
version: '3.9'

# Include the development configuration by default
include:
  - docker/docker-compose.dev.yml