# Memory Nexus Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Memory Nexus application metrics
  - job_name: 'memory-nexus'
    static_configs:
      - targets: ['memory-nexus:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # SurrealDB metrics
  - job_name: 'surrealdb'
    static_configs:
      - targets: ['surrealdb:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Qdrant metrics
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']